# MCPJungle Docker Compose configuration for individual users.
# Use this compose file if you want to run MCPJungle locally for your personal MCP management & Gateway.
# The mcpjungle server runs in development mode.
services:
  db:
    image: mysql:8.0
    container_name: mcpjungle-db
    environment:
      MYSQL_USER: mcpjungle
      MYSQL_PASSWORD: mcpjungle
      MYSQL_DATABASE: mcpjungle
      MYSQL_ROOT_PASSWORD: rootpassword
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mcpjungle:
    image: ghcr.io/mcpjungle/mcpjungle:${MCPJUNGLE_IMAGE_TAG:-latest-stdio}
    container_name: mcpjungle-server
    environment:
      DATABASE_URL: mysql://mcpjungle:mcpjungle@db:3306/mcpjungle
      SERVER_MODE: ${SERVER_MODE:-development}
      OTEL_ENABLED: ${OTEL_ENABLED:-false}
      MCP_SERVER_INIT_REQ_TIMEOUT_SEC: ${MCP_SERVER_INIT_REQ_TIMEOUT_SEC:-10}
    ports:
      - "${HOST_PORT:-8080}:8080"
    volumes:
      # Mount host filesystem current directory to enable filesystem MCP server access
      - .:/host:ro
      # Other options:
      # - ${HOME}:/host/home:ro
      # - /tmp:/host/tmp:rw
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  db_data:
